### ISSUE TITLE
Automatically copy when published / updated

### ISSUE THREAD

**Issue by dappi** [aucor/aucor-polylang-translation-mapper#1]
Is it possible to modify the plugin to automatically to create copies to other languages when post is published / updated? And on update, also synch the data to other already existing translations?

**Comment by TeemuSuoranta** [comment]
Hi!

I have another plugin that could be more suitable for that kind of use https://github.com/aucor/polylang-copy-content

I'll keep this mapper just as a mapper that you'll run once when importing posts.

The other plugin, Polylang Copy Content copies the content and title, translates and re-inserts all media inside content when creating a translation for post. If you'll look into source code of that plugin, there's the filter "polylang_addon_copy_content" that you can maybe use outside of the plugin (haven't tested it, though). Polylang copies all post_meta by default so my plugin doesn't take care of that.

So I could make filters so you can extend the functionality but I would keep the syncing and automatical copy creation outside of the plugin because they will vary from case to case very much and create a lot of complexity. Some issues are for example:
- When to override existing content on sync?
- How to avoid duplicate content problems in SEO perspective?
- How to limit this to certain post type, language, taxonomy etc
- How to limit syncing to only certain post_meta keys etc

Polylang has by default some syncing options and I'd recommend to check them out and trying to find out if you can extend those. If you'll know your way around WordPress, tt shouldn't be too hard to implement this functionality on your own, as you can attach to update_post action, iterate through all languages and use wp_insert_post function to create copies and finally connect them with the Polylang's pll_save_post_translations function.

**Comment by dappi** [comment]
Thanks, I willl take look at those. Though I got message from Polylang developer that 2.1 Pro version will be able to show same content for multiple language which actually would solve my problem.
